Footer docs to mdx
brainly/style-guide pull request #2383
Opened 2022-04-08 14:16 UTC by katarzynatobis

Convert Footer documentation to mdx

2022-04-08 15:06 UTC, coderitual approved these changes

2022-04-11 13:31 UTC, coderitual commented
@katarzynatobis Probably we need better visual example of this component, even though I am not sure if this component is even used on prod. I think we need better footer component than this one at some point.
![CleanShot 2022-04-11 at 15 31 01](https://user-images.githubusercontent.com/8572321/162750396-df40d40b-6bda-43ba-b813-78a758716c9a.png)

2022-04-11 14:42 UTC, katarzynatobis commented
@coderitual I totally agree! Footer is not used on prod, but it definitely needs some better presentation. I added a story with some 'real' footer content, but without any other styleguide component/

2022-04-11 14:56 UTC, domidomi requested changes

2022-04-11 14:56 UTC, domidomi commented on src/components/footer/Footer.stories.mdx
> +      <Footer>
@katarzynatobis Can you please pass `args` to Footer?

2022-04-12 09:52 UTC, merged