Newsletter April 2022
brainly/style-guide pull request #2390
Opened 2022-04-13 15:29 UTC by domidomi

2022-04-19 08:30 UTC, coderitual commented on newsletter/2022-April-vX.md
> +- Storybook deployment for each PR now available
deployment and **preview**

2022-04-19 09:43 UTC, katarzynatobis commented on newsletter/2022-April-vX.md
> +  - Added onItemSelect handler to dropdown #2327
this doesn't belong to Dialog improvements

2022-04-19 09:57 UTC, katarzynatobis commented on newsletter/2022-April-vX.md
> +  - Pass target to link (#2379)
+ separators accessibility improvements

2022-04-19 10:00 UTC, clxandstuff requested changes

2022-04-19 10:55 UTC, clxandstuff commented on newsletter/2022-April-vX.md
> +- Responsive props documentation for components
Its on line 18

2022-04-25 09:41 UTC, clxandstuff approved these changes

2022-04-25 09:43 UTC, merged