Newsletter January 2023
brainly/style-guide pull request #2646
Opened 2023-01-19 16:37 UTC by domidomi

2023-01-20 08:44 UTC, katarzynatobis requested changes

2023-01-20 08:44 UTC, katarzynatobis commented on newsletter/v221.1.0-January-2023.mdx
> +- [StyleGuide Live Editor](<#-styleguide-live-editor-(beta-version)>)
Wrong link, some weird characters :)

2023-01-20 08:44 UTC, katarzynatobis commented on newsletter/v221.1.0-January-2023.mdx
> +We've created a tool that visualizes StyleGuide components usage.
I would add that this is internal, only for Brainly (both access and data).

2023-01-20 08:44 UTC, katarzynatobis commented on newsletter/v221.1.0-January-2023.mdx
> +Components using `focusTextStyle`: `Link`, `Checkbox`, `Radio`, `Select`, `Dropdown`, `Search`, `Textarea`, native `<a>`.
Only Link, Dropdown, and <a> use `focusTextStyle`. My bad, I didn't update the description after changes 🙈

2023-01-20 08:44 UTC, katarzynatobis commented on newsletter/v221.1.0-January-2023.mdx
> +- added high contrast mode for Button (#2540)
PR number was overlooked, I think it should be removed

2023-01-25 11:45 UTC, coderitual approved these changes

2023-01-25 11:59 UTC, clxandstuff approved these changes

2023-01-25 12:23 UTC, katarzynatobis approved these changes

2023-01-25 12:52 UTC, merged