Chips component
brainly/style-guide pull request #2715
Opened 2023-04-07 12:28 UTC by katarzynatobis

2023-04-12 10:17 UTC, clxandstuff requested changes

2023-04-12 10:17 UTC, clxandstuff commented on src/components/chip/ChipGroup.spec.tsx
> +      const chipGroup = renderChipGroup({});
You don't have to assign result of render to variable

2023-04-12 10:18 UTC, clxandstuff commented on src/components/chip/ChipGroup.spec.tsx
> +      const chipGroup = renderChipGroup({
When disabled, chip should not have press effect

https://user-images.githubusercontent.com/25419830/231428799-06c9ef40-4199-4407-9c02-0016314bfde6.mov

2023-04-12 10:19 UTC, clxandstuff commented on src/components/chip/ChipGroup.spec.tsx
> +      const chipGroup = renderChipGroup({
In Firefox cross is misaligned.

![Screenshot 2023-04-12 at 12 17 18](https://user-images.githubusercontent.com/25419830/231428960-e2ddbf2e-1d72-44ec-89e7-e593462c1481.png)

2023-04-13 10:51 UTC, clxandstuff commented
Code looks good. The only thing left is this misaligned cross on Firefox.

2023-04-13 10:53 UTC, clxandstuff reviewed
Code looks good. The only thing left is this misaligned cross on Firefox.

2023-04-13 16:08 UTC, katarzynatobis commented
@clxandstuff could you check now?

2023-04-14 07:56 UTC, clxandstuff commented
@katarzynatobis now it works, good job! 😄

2023-04-14 07:56 UTC, clxandstuff approved these changes

2023-04-19 11:26 UTC, merged